### PR TITLE
Handle new KWin API for kde-backend.

### PR DESCRIPTION
**Pull request by N4tus**
I have put up the required changes that should be enough to support both versions. BUT I don't have a newer KDE installation and I need someone else to test it. (That is why it's currently WIP). It does work for me at least.

The Kwin-Script dispatches based on the comment that was linked in the issue and for starting the script I just try out both paths.

#433

### CODE REVIEW

**Comment by k0kubun** [comment]
By the way, as I raised at https://github.com/k0kubun/xremap/issues/393#issuecomment-1879834308 before, would you be interested in being a maintainer for the KDE client?

**Comment by Ahrotahn** [comment]
These changes are functional when I tested them on my plasma 6 system.

**Comment by N4tus** [comment]
Since @Ahrotahn confirmed that it works on plasma 6, I think we can merge it.  Although it also would be interesting to know if #393 was also fixed with this PR. But even if not, supporting kde6 is still an improvement.

Also to answer your Question @k0kubun: You can count me as maintainer for the KDE-Client.

**Comment by k0kubun** [comment]
> Also to answer your Question @k0kubun: You can count me as maintainer for the KDE-Client.

Thanks! I transferred this repository to the xremap org and invited you to it to give you write access to this repository. Please accept the invitation when you have a chance.

**Comment by k0kubun** [comment]
Thanks for working on this. 

By the way, the release is fully automated using git tags, so you can cut a release too. Write up a CHANGELOG entry, update versions in Cargo.toml/lock, make a commit, tag it with `vX.Y.Z`, and push the tag and branch.

```bash
git commit -m "Version 0.8.16"
git tag v0.8.16
git push origin master && git push origin --tags
```

**Pull request merged**
