### PR TITLE
wlroots client support window title match

### PR DESCRIPTION
**Pull request by jixiuf**
demo:
```
  - name: kitty emacs
    application:
      only: [kitty]
    window:
      only: /GNU\/Emacs/
    remap:
      super-C-w: [C-x ,k] 
      
  - name: kitty
    application:
      only: [kitty]
    remap:
      super-C-w: super-C-q
```
When the terminal window title match `GNU/Emacs` (when I run `emacs -nw` in kitty)  ,`super-C-w` would send `C-x k` 
else it would send `super-C-q`

currently only `wlroots client` is supported 
https://github.com/xremap/xremap/issues/150 related

### CODE REVIEW

**Review by k0kubun — APPROVED** [review]
Nice, thanks!

**Comment by k0kubun** [comment]
Out of curiosity, would you be interested in being a maintainer for the wlroots client?

**Comment by jixiuf** [comment]
> Out of curiosity, would you be interested in being a maintainer for the wlroots client?

Ok, my pleasure.

**Comment by k0kubun** [comment]
Thanks! I invited you to xremap org. 

I already released it myself this time, but you may cut a release next time, e.g.

```bash
git commit -m "Version 0.8.16"
git tag v0.8.16
git push origin master && git push origin --tags
```

**Pull request merged**
